version: '3.4'

services:
  api:
    build: api
    # command: uwsgi app.ini
    container_name: api
    environment:
    - FLASK_ENV=development
    expose:
    - 5000
    volumes: 
    - /home/user/energy:/home/user/energy
  nginx:
    build: nginx
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/conf.d/default.conf
    container_name: nginx
    restart: on-failure
    ports:
    - 80:80
